storage:
  file: data.yml

default-group: membro

# Cores que podem ser escolhidas para o texto enviado pelo jogador.
# Estas cores NÃO alteram a cor do nickname nem a cor do cargo.
chat:
  default-color: branco
  colors:
    branco: "&f"
    cinza: "&7"
    vermelho: "&c"
    vermelho-escuro: "&4"
    verde: "&a"
    verde-escuro: "&2"
    azul: "&9"
    azul-claro: "&b"
    amarelo: "&e"
    dourado: "&6"
    rosa: "&d"
    roxo: "&5"
    aqua: "&3"

# A cor do cargo é definida em name-color.
# Essa mesma cor é aplicada ao prefixo/cargo, nickname e futuramente ao TAB.
# Não existe uma cor separada para o nickname.
hierarchy:
  - membro
  - ajudante
  - moderador
  - administrador
  - gerente
  - dono

groups:
  membro:
    display-name: "Membro"
    prefix: ""
    name-color: "branco"
    permissions:
      - chatplus.local
    parents: []
  ajudante:
    display-name: "Ajudante"
    prefix: "&e[Ajudante] "
    name-color: "amarelo"
    permissions:
      - chatplus.local
      - chatplus.staff
    parents:
      - membro
  moderador:
    display-name: "Moderador"
    prefix: "&2[Moderador] "
    name-color: "verde-escuro"
    permissions:
      - chatplus.local
      - chatplus.staff
    parents:
      - ajudante
  administrador:
    display-name: "Administrador"
    prefix: "&c[ADM] "
    name-color: "vermelho"
    permissions:
      - chatplus.local
      - chatplus.global
      - chatplus.staff
    parents:
      - moderador
  gerente:
    display-name: "Gerente"
    prefix: "&6[Gerente] "
    name-color: "dourado"
    permissions:
      - chatplus.local
      - chatplus.global
      - chatplus.staff
    parents:
      - administrador
  dono:
    display-name: "Dono"
    prefix: "&4[Dono] "
    name-color: "vermelho-escuro"
    permissions:
      - chatplus.local
      - chatplus.global
      - chatplus.staff
      - chatplus.admin
      - cargoplus.promover
      - cargoplus.setcargo
      - cargoplus.removercargo
      - cargoplus.admin
      - chatplus.cor
      - utilidadesplus.plugins
      - utilidadesplus.configurar
      - utilidadesplus.motd.admin
    parents:
      - gerente
